#! zsh

emulate -L zsh

local -a null

zparseopts -D -a null -- \
    -version \
    -help \
    C: \
    c: \
    -exec-path:: \
    -html-path \
    -man-path \
    -info-path \
    p -paginate \
    -no-pager \
    -git-dir: \
    -work-tree: \
    -namespace \
    -bare \
    -no-replace-objects \
    -literal-pathspecs \
    -glob-pathspecs \
    -noglob-pathspecs \
    -icase-pathspecs

if [[ $# == 0 ]]; then
    man git
else
    local als=$(git config --get "alias.$1")
    man git-${als:-$1}
fi

### That's all, folks!
