#! zsh

emulate -L zsh

local -a null

zparseopts -D -a null -- \
    A -askpass \
    b -background \
    C: -close-from: \
    E -preserve-env \
    e -edit \
    g: -group: \
    H -set-home \
    h:: -host: -help \
    i -login \
    K -remove-timestamp \
    k -reset-timestamp \
    l -list \
    n -non-interactive \
    P -preserve-groups \
    p: -prompt: \
    r: -role: \
    S -stdin \
    s -shell \
    t: -type: \
    U: -other-user: \
    u: -user: \
    V -version \
    v -validate

if [[ $1 == -* ]]; then
    man sudo
    print -Plu2 "" "Unknown option '%B$1%b' for sudo"
    return 1
fi

man ${1:-sudo}

return $?

### That's all, folks!
